name: gymumity
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  app_links: ^6.4.0
  badges: ^3.1.2
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  calendar_date_picker2: ^2.0.1
  carousel_slider: ^5.0.0
  chewie: ^1.8.5
  clipboard: ^2.0.2
  collection: ^1.18.0
  color_filter_extension: ^1.0.1
  colorfilter_generator: ^0.0.8
  country_code_picker: ^3.1.0
  country_phone_validator: ^1.0.1
  crop_your_image: ^2.0.0
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  device_preview_plus: any
  dio: ^5.7.0
  dotted_border: ^3.0.1
  dropdown_search: ^6.0.1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_html: ^3.0.0-beta.2
  flutter_image_filters: ^0.0.25
  flutter_local_notifications: ^19.1.0
  flutter_map: ^8.1.1
  flutter_native_splash: ^2.4.4
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_sound: ^9.28.0
  flutter_svg: ^2.0.16
  flutter_time_picker_spinner: ^2.0.0
  gal: ^2.3.0
  geolocator: ^14.0.1
  get_it: ^8.0.2
  go_router: ^16.3.0
  google_maps_flutter: ^2.12.2
  google_sign_in: ^7.2.0
  hugeicons: ^1.1.1
  image: ^4.5.4
  image_cropper: ^11.0.0
  image_editor: ^1.6.0
  image_picker: ^1.1.2
  intl: ^0.19.0
#  intl_phone_number_input: ^0.7.4
  introduction_screen: ^4.0.0
  latlong2: ^0.9.1
  logger: ^2.5.0
  lottie: ^3.2.0
  nb_utils: ^7.0.7
  open_file: ^3.5.10
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  persistent_bottom_nav_bar_v2: ^6.2.0
  photo_manager: ^3.6.4
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  readmore: ^3.0.0
  sentry_flutter: ^9.7.0
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.0+3
  syncfusion_flutter_charts: ^31.1.19
  syncfusion_flutter_pdfviewer: ^31.1.19
  timeago: ^3.7.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_editor_2: ^3.1.1
  video_player: ^2.4.0
  youtube_player_flutter: ^9.1.1
  stream_transform: ^2.1.1
  date_picker_timeline: ^1.2.7
  geocoding: ^4.0.0

  # For firebase
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_pagination: ^4.1.0
  webview_flutter: ^4.13.0
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^12.0.1
  rxdart: ^0.28.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.5

dependency_overrides:
  intl: ^0.19.0
  dotted_border: ^3.0.0
  get_thumbnail_video: ^0.7.3

dev_dependencies:
  change_app_package_name: ^1.5.0
  dependency_validator: ^5.0.3
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/placeholder.webp
    - assets/images/fayyad/
    - assets/logo/
    - assets/svgs/
    - assets/translations/
    - assets/lottie/
    - assets/images/steps/
    - assets/images/accounts/
    - assets/images/splash/
    - assets/svgs/nav_bar_icons/
    - assets/gifs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/static/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Roboto/static/Roboto-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/static/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/static/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/static/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto/static/Roboto-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/static/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto/static/Roboto-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/static/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

    - family: RobotoVariable
      fonts:
        - asset: assets/fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic